SELECT USERS.*, ADDRESS.ADDRESSTEXT FROM
USERS,ADDRESS
WHERE USERS.ID=ADDRESS.USERID
AND USERS.ID=1  --ÝKÝ TABLOYU BASÝT BÝR YÖNETEMLE BÝRLEÞTÝRME


SELECT USERS.NAMESURNAME,USERS.EMAIL,USERS.GENDER,USERS.BIRTHDATE ,ADDRESS.ADDRESSTEXT FROM
USERS,ADDRESS
WHERE USERS.ID=ADDRESS.USERID
AND USERS.ID=1   --BURADA ÝSE USERS TABLOSUNDAN ÝSTEDÝÐÝMÝZ DEÐERLERÝ ÇEKTÝK 

--BU ÝÞLEMÝ UZUN UZUN YAZMAK YERÝNE ALIAS KULLANARAK DAHA KISA KELÝMELERLE DÜZENLEYEBÝLÝRZ
SELECT U.NAMESURNAME,U.EMAIL,U.GENDER,U.BIRTHDATE ,A.ADDRESSTEXT FROM
USERS U,ADDRESS A
WHERE U.ID=A.USERID
AND U.ID=5  --USERS U HARFÝ ÝLE ADDRESS A HARFÝ ÝLE KISALTMIÞ OLDUK

SELECT U.NAMESURNAME AS ADSOYAD,U.EMAIL MAÝLADRESÝ,U.GENDER CÝNSÝYET,U.BIRTHDATE DOGUMTARÝHÝ,A.ADDRESSTEXT AS ACIKADRES FROM
USERS U,ADDRESS A
WHERE U.ID=A.USERID
AND U.ID=10  --AS ÝLE KOLON ÝSÝMLERÝNÝ DEÐÝÞTÝRDÝK