USE ETRADE

SELECT * FROM CUSTOMERS

INSERT INTO CUSTOMERS 
(CUSTOMERNAME,CITY,BIRTHDATE,DISTRICT,GENDER)
VALUES
('AYÞE ALDAÞ','MALATYA','1978-08-15','KALE','K')

SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS SET NATION='TR' , AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

/* datedýff ile veritabanýmýzdaki tüm tarihleri bugünün tarihi ile çýkartýp gerçek yaþý buluruz*/


/* DELETE---- DELETE FROM CUSTOMERS--- ÞEKLÝNDE ÇALIÞIR*/

SELECT * FROM CUSTOMERS
/*TRUNCATE--- TRUNCATE TABLE CUSTOMERS--- ÞEKLÝNDE KULLANILIR. 
Temel mantýðý DELETE komutundan daha hýzþý çalýþýr ve tablo ilk haline döner,
yeni DELETE komutu ile silme yaptýktýktan sonra INSERT iþlemi gerçekleþtiðinde
kaldýðý id den devam eder örneðin 15 kayýt var tabloyu temizledik sonra insert attýk
ve kayýt 16 dan devam eder ama TRUNCATE komutunda sýfýrlar ve 1den yeniden baþlatýr. */ 


/*WHERE ÞARTI
<> EÞÝT DEÐÝLDÝR
BETWEEN : ARASINDA AND 
LIKE : ÝLE BAÞLAR,ÝLE BÝTER, ÝÇERÝR---TERSÝ ÝÇÝN NOT LIKE
IN : ÝÇÝNDEDÝR-----TERSÝ ÝÇÝN NOT IN   */

SELECT * FROM CUSTOMERS
/*WHERE CUSTOMERNAME='Nazife DEVE'*/
/*WHERE CITY='Malatya'*/
/* WHERE CITY <> 'Ýzmir' izmir harici  WHERE NOT CITY= 'ÝZMÝR'*/
/*WHERE BIRTHDATE < '1999-01-01'  WHERE BIRTHDATE> '19900101' ÞEKLÝNDE DE YAZABÝLÝRÝZ*/

/*WHERE BIRTHDATE BETWEEN '19900101' AND '19950805'
WHERE AGE BETWEEN '20' AND '35'
WHERE CUSTOMERNAME LIKE 'ALÝ%' ALÝ ÝLE BAÞLAYANLAR  NOT LÝKE ÝSE BAÞLAMAYANLAR
'%ALÝ%' ÝÇÝNDE ALÝ OLANLAR YANÝ KALIP 
'%ALÝ' ALÝ ÝLE BÝTENLER*/

/*WHERE CITY  IN ('ISTANBUL','ANKARA','MALATYA') þehirleri seçili olanlarý getirir
WHERE CITY NOT IN ('ISTANBUL','ANKARA','MALATYA') seçili þehirler hariç diðer þehirleri getirir*/
SELECT * FROM CUSTOMERS
/*UPDATE CUSTOMERS SET GENDER = 'ERKEK' WHERE GENDER ='E'  E ÝLE BELÝRTÝLEN CÝNSÝYETÝ ERKEK OLARAK DEÐÝÞTÝRDÝK*/
UPDATE CUSTOMERS SET GENDER = 'KADIN' WHERE GENDER ='K'

/*SELECT * FROM CUSTOMERS WHERE ID=18
DELETE FROM CUSTOMERS WHERE ID = 18  ID 18 OLAN KÝÞÝYÝ SÝLERÝZ*/

SELECT * FROM CUSTOMERS
/*AND OPERATÖRÜ VERÝLEN ÝKÝ ÞARTA DA UYMAK ZORUNDA*/

/*OR OPERATÖRÜ VERÝLEN ÝKÝ ÞARTTAN HERHANGÝBÝRÝNÝ KARÞILAMALI*/

/*WHERE CITY='ÝSTANBUL' AND DISTRICT ='BEYLÝKDÜZÜ' AND AGE='82'*/

/*WHERE CITY = 'ÝSTANBUL' AND GENDER ='ERKEK' 
AND BIRTHDATE BETWEEN '19900101' AND '20000101'*/

/* OR OPERATÖRÜ UYGULMALARI*/
SELECT * FROM CUSTOMERS
--WHERE CITY = 'ÝSTANBUL' OR CITY='ÝZMÝR' AND GENDER NOT IN ('ERKEK') --BURADA AND KULLANDIÐIMIZ ÝÇÝN ÝZMÝR ERKEKLERÝ GETÝRMEZ
--WHERE BIRTHDATE <='19900101' OR BIRTHDATE>= '19951231'

/*DISTINCT KOMUTU TEKRAR EDEN SATIRLARI TEKÝLLEÞTÝRMEK */

SELECT DISTINCT CITY FROM CUSTOMERS  --þehirlerin hepsini bir kere getirdik

SELECT CITY, DISTRICT FROM CUSTOMERS WHERE CITY='ÝSTANBUL' --ÝSTANBUL ÞEHRÝNDEKÝ ÝLÇELER

SELECT DISTINCT CITY, DISTRICT FROM CUSTOMERS WHERE CITY='ÝSTANBUL' --ÝLÇELERÝ TEKÝLLEÞTÝRDÝK

--ORDER BY KOMUTU
SELECT * FROM CUSTOMERS
--ORDER BY ID ASC KÜÇÜKTEN BÜYÜÐE
--ORDER BY ID DESC BÜYÜKTEN KÜÇÜÐE
--ORDER BY CUSTOMERNAME DESC  ÝSÝMLERÝN BAÞ HARFLERÝNE GÖRE
--ORDER BY DISTRICT ASC--DESC 
--ORDER BY BIRTHDATE DESC --ASC
--ORDER BY CITY ,DISTRICT --ÞEHÝRLERÝ SIRALADI SONRA ÝLÇELERÝ ÝÇLERÞNDE SIRALADI

--ORDER BY BIRTHDATE ,AGE
--ORDER BY CITY ,DISTRICT,CUSTOMERNAME ÞEHÝRLERÝ SIRALAR ÝLÇELERÝ SIRALAR ÝLÇELERDEKÝ ÝSÝMLERÝ KENDÝ ÝÇÝNDE SIRALAR
--ORDER BY CITY ASC ,CUSTOMERNAME DESC
SELECT * FROM CUSTOMERS
--WHERE CITY ='ÝSTANBUL'
--ORDER BY CITY ,DISTRICT,CUSTOMERNAME

--ORDER BY 2 --iKÝNCÝ KOLONA GÖRE SIRALADI

WHERE CITY ='ÝSTANBUL'
ORDER BY 5,2

SELECT TOP 100 *FROM  CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT TOP 100 PERCENT *FROM  CUSTOMERS   --KAYITLARIN YÜZDE YÜZÜNÜ GETÝRÝR
ORDER BY CUSTOMERNAME