--AYLARA GÖRE ÞEHÝRLERDEKÝ SATIÞ DURUMU
SELECT CITY,MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
/*GROUP BY MONTHNAME_
ORDER BY MONTHNAME_ */ --TÜM ÞEHÝRLERÝN AYLRA GÖRE SATIÞ DAÐILIMI

GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_  --ÞEHÝRLERE GÖRE AYLARIN SATIÞ ORANI
