USE ETRADE2

SELECT * FROM CUSTOMERS

SELECT DISTINCT CITY  FROM CUSTOMERS
SELECT * FROM SALES

--AGGREGATE FUNCTIONS  SUM,COUNT,MIN,MAX,AVG

SELECT COUNT(*) FROM SALES

SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(*) ,SUM (AMOUNT),AVG(AMOUNT)FROM SALES

SELECT * FROM SALES ORDER BY TOTALPRICE DESC 

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO) ,SUM (TOTALPRICE),AVG(TOTALPRICE)FROM SALES

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO) ,SUM (TOTALPRICE),AVG(TOTALPRICE)FROM SALES
WHERE CITY='ADANA'

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO) ,SUM (TOTALPRICE),AVG(TOTALPRICE)FROM SALES
WHERE CITY='MALATYA'

--GROUP BY

SELECT CITY, MIN(TOTALPRICE) AS MINPRICE,MAX(TOTALPRICE) AS MAXPRICE,
COUNT(FICHENO) ROWCOUNT_ ,SUM (TOTALPRICE) AS TOTALPRICE,AVG(TOTALPRICE) AS AVGPRICE
FROM SALES GROUP BY CITY
ORDER BY SUM (TOTALPRICE)

SELECT TOP 10 CITY , SUM(TOTALPRICE) AS TOTALPRICE FROM SALES GROUP BY CITY 
ORDER BY SUM(TOTALPRICE) DESC 
