--BELLÝ BÝR CÝRONUN ÜZERÝNDE SATIÞ YAPAN MAÐAZALARI GETÝRME

SELECT CITY , SUM(TOTALPRICE) 
FROM SALES  
GROUP BY CITY
ORDER BY SUM (TOTALPRICE) DESC -- BURADA ÞEHÝRLERÝN TOPLAM SATIÞLARINI BÜYÜKTEN KÜÇÜÐE SIRALADIK

SELECT CITY , SUM(TOTALPRICE) 
FROM SALES  
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM (TOTALPRICE) DESC  --BURADA ÝSE 40000 DEN BÜYÜK OLANLARI GETÝRDÝK AGGREGATE FONKSÝYONLARDA WHERE KULLANAMAYACAÐIMIZ ÝÇÝN HAVING KULLANDIK 
