use ETRADE2
/**SELECT*,CONVERT(DATE,DATE_) AS DATE2
FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_
--DATA DA SAAT VE TARÝH AYNI SÜTUNDA BUNU TEKÝLLEÞTÝRMEK ÝÇÝN
--CONVERT ÝLE ÝKÝYE BÖLERÝZ AMA BU SADECE SORGU ÇALIÞTIÐI ZAMAN GELÝR
--YANÝ AYRI BÝR SÜTUN TEMELLÝ OLARAK DATA YA EKLENMEZ**/

--þimdi tablomuza date alanýný ekledik ve update iþlemini gerçekleþtiricez

UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)

SELECT*FROM SALES

SELECT CITY, DATE2,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES WHERE CITY ='ANKARA'
GROUP BY CITY,DATE2
ORDER BY CITY,DATE2