--MAÐAZALARIN MÜÞTERÝ SAYILARINI GETÝRME
SELECT FICHENO, COUNT(*)
FROM SALES WHERE MONTHNAME_ ='01.OCAK'
AND CITY='ADANA'
GROUP BY FICHENO

--BÝR FÝÞTE BÝRDEN FAZLA ÜRÜN OLDUÐU ÝÇÝN FÝÞ SAYISI FAZLAYDI
--ÞÝMDÝ ÝSE FÝÞ SAYISINA KESÝLEN ÜRÜN ADEDÝNÝ SAYDIRDIÐIMIZ ÝÇÝN SADECE ADET OLARAK FÝÞ SAYISINI ALDI 


SELECT CITY, COUNT(DISTINCT FICHENO)
FROM SALES WHERE MONTHNAME_ ='01.OCAK'

GROUP BY CITY
ORDER BY CITY    --ÞEHÝRLERDE OCAK AYINDA KESÝLEN FÝÞ ADEDÝ


---BÝR MAÐAZANIN TEKÝL MÜÞTERÝ ADEDÝ
SELECT CITY, COUNT(DISTINCT CUSTOMERNAME) AS UNIQECUSTOMER,
COUNT(DISTINCT FICHENO) CUSTOMERCOUNT,
COUNT(*) ITEMCOUNT
FROM SALES WHERE MONTHNAME_ ='01.OCAK'

GROUP BY CITY
ORDER BY CITY 
