--29.04.03 cts

USE ETRADE2
--ÝLLERÝN SATIÞI
SELECT CITY, DATE2,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES 
WHERE DATE2='2019-01-01'

GROUP BY DATE2,CITY
ORDER BY DATE2,SUM(TOTALPRICE) DESC


select* from sales where CITY='ANKARA'
order by DATE_