SELECT U.NAMESURNAME,U.EMAIL,U.GENDER,U.BIRTHDATE,
C.COUNTRY ULKE ,CT.CITY SEHIR, T.TOWN ILCE, D.DISTRICT SEMT,
A.POSTALCODE POSTAKODU,
A.ADDRESSTEXT FROM
USERS U,ADDRESS A,COUNTRIES C, CITIES CT,TOWNS T,
DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
--AND U.ID=4
AND CT.CITY LIKE'ÝZMÝR'
ORDER BY U.NAMESURNAME