
USE ETRADE4

--SELECT DATEDIFF(DAY, NEXT_SIPARISTARIH,FATURATARIHI) AS GUN_FARK
SET STATISTICS IO ON

SELECT
  
	U.USERNAME_ AS KULLANICIADI,
    U.NAMESURNAME AS ADSOYAD,
    O.ID AS SIPARISID,
    O.DATE_ AS SIPARIS_TARIH,
    P.DATE_ AS ODEMETARIHI,
    I.DATE_ AS FATURATARIHI,
	lead(O.DATE_,1,null) OVER (ORDER BY O.ID ASC) as NEXT_SIPARISTARIH,
	--lag(p.date_,1,null) OVER (ORDER BY O.ID ASC) as NEXT_odemeTARIH,
	DATEDIFF(day, O.DATE_, lead(O.DATE_) OVER (ORDER BY O.DATE_)) AS GunFarki,
	CASE
		WHEN DATEDIFF(day, O.DATE_, lead(O.DATE_) OVER (ORDER BY O.DATE_)) < 30 THEN '1'
        WHEN DATEDIFF(day, O.DATE_, lead(O.DATE_) OVER (ORDER BY O.DATE_)) > 90 THEN '0'
        ELSE '2'	
	END AS KARSÝLASTÝRMA	
FROM 
	ORDERS O 
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	
WHERE 
	U.NAMESURNAME='Talha CANIKARA'
--SÝPARÝÞ TARHÝ TARÝHÝ VE FATURA TARÝHÝ KARÞILAÞTIR
