--FORMAT 
SELECT FORMAT(GETDATE(),'d','en-us')
SELECT FORMAT(GETDATE(),'D','en-us')


--LEFT RIGHT LEN

SELECT LEFT('SÜMEYYE KARAKAÞ',4)
SELECT RIGHT('SÜMEYYE KARAKAÞ',4)
SELECT LEN('1234567890')


SELECT LEFT('SÜMEYYE KARAKAÞ',7)
SELECT RIGHT('SÜMEYYE KARAKAÞ',7)

SELECT LEFT('SÜMEYYE KARAKAÞ',CHARINDEX(' ','SÜMEYYE KARAKAÞ'))
SELECT RIGHT('SÜMEYYE KARAKAÞ',LEN('SÜMEYYE KARAKAÞ')-CHARINDEX(' ','SÜMEYYE KARAKAÞ'))

SELECT
LEFT(NAMESURNAME,CHARINDEX(' ',NAMESURNAME)),RIGHT(NAMESURNAME,LEN(NAMESURNAME)-CHARINDEX(' ',NAMESURNAME)),
*FROM USERS


