USE ETRADE4

--SUBSTRING

SELECT*FROM USERS WHERE USERNAME_ LIKE 'A%'
SELECT*FROM USERS WHERE SUBSTRING(USERNAME_,1,1)='A'



SELECT*FROM USERS WHERE USERNAME_ LIKE '%E'
SELECT*FROM USERS WHERE SUBSTRING(USERNAME_,LEN(USERNAME_),1)='E'


--CHARINDEX METÝN ÝÇERÝSÝNDE ÝSTEDÐÝMÝZÝ ARAR

SELECT CHARINDEX('Y','SÜMEYYE KARAKAÞ',1) --ÇIKTI 6

--CONCAT STRÝNG BÝRLEÞTÝRME
SELECT 'SÜMEYYE'+'KARAKAÞ'
SELECT CONCAT('SÜMEYYE','KARAKAÞ') --SEPARATOR ÝHTÝYACINI KARÞILAMAK ÝÇÝN YENÝ SÜRÜMÜ GELMÝÞTÝR
SELECT CONCAT_WS(' ','SÜMEYYE','KARAKAÞ')


SELECT CONCAT_WS(' ',USERNAME_,PASSWORD_,NAMESURNAME),*FROM USERS

