--TRIM,LTRIM,RTRIM  BOÞLUKLARI TEMÝZLE
SELECT TRIM(' SÜMEYYE KARAKAÞ ')
SELECT LTRIM(' SÜMEYYE KARAKAÞ ')
SELECT RTRIM(' SÜMEYYE KARAKAÞ ')

SELECT LTRIM(RTRIM(' SÜMEYYE KARAKAÞ '))


--LOWER, UPPER,REVERSE,REPLICATE

SELECT LOWER('SÜMEYYE')
SELECT UPPER('Sümeyye')
SELECT REVERSE('SÜMEYYE')
SELECT REPLICATE('0',10)

SELECT*,
REPLICATE('0',8-LEN(SIRANO))+CONVERT(VARCHAR,SIRANO)
FROM TEST
UPDATE TEST SET SIRANO2=REPLICATE('0',8-LEN(SIRANO))+CONVERT(VARCHAR,SIRANO)

SELECT*FROM TEST




