--KULLANICININ SON ADRESÝNÝ BULMA
USE ETRADE4
SELECT U.*,A.ADDRESSTEXT,A.ID FROM
USERS U
INNER JOIN ADDRESS A ON U.ID=A.USERID

WHERE U.ID=1
ORDER BY A.ID DESC
--BU KÝÞÝNÝN 4 ADET ADRESÝ BULUNMAKTADIR EN SON ADRESÝNE ERÝÞMEK ÝÇÝN ÝSE SUBQUERY KULLANMAMIZ LAZIM

SELECT U.*,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID DESC) SONADRES,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID ) ILKADRES,
(SELECT COUNT(ADDRESSTEXT) FROM ADDRESS WHERE USERID=U.ID) ADRESSAYISI
FROM
USERS U