USE ETRADE4
SET STATISTICS IO ON --BU SORGU ÝLE OKUMA ZAMANINI ÖÐRENEBÝLÝRÝZ
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI
FROM 
ITEMS ITM --KAÇ TANE ÜRÜN OLDIUÐUNU GÖRDÜK

SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUKSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMADET
FROM 
ITEMS ITM
ORDER BY ITM.ITEMNAME


--SUBQUERY ÝÇ ÝÇE SELECT DEMEKTÝR YANÝ ÝÇ ÝÇE SORGULARIN ÇEKÝLMESÝDÝR. JOIN ÝÞLEMÝ GÝBÝDÝR
--ÇOK FAZLA ÝÇ ÝÇE SORGU YAZMAK YERÝNE JOIN ÝÞLEMLERÝNÝ KULLANIRSAK DAHA AZ ZAMAN HARCARIZ SORGUMUZUN PERFORMANSI YÜKSEK OLUR

