USE ETRADE3
SELECT U.NAMESURNAME, COUNT(A.ID) AS ADRESSAYISI ,COUNT(DISTINCT C.COUNTRY) AS ULKESAYISI FROM  --KULLANICILARIN AKTÝF ADRES SAYISI
--TEKRAR ETMEYEN KAYITLAR ÝÇÝN DISTINCT
--COUNT(DISTINCT U.NAMESURNAME)KULLANICI SAYISI

USERS U,ADDRESS A,COUNTRIES C, CITIES CT,TOWNS T,
DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID

GROUP BY U.NAMESURNAME

HAVING COUNT(A.ID)>2



USE ETRADE3
SELECT CT.CITY ,COUNT(U.ID) AS KULLANICISAYISI,COUNT(DISTINCT D.DISTRICT) AS ILCESAYISI--ÞEHÝRLERE GÖRE KULLANICI SAYISI
FROM
USERS U,ADDRESS A,COUNTRIES C, CITIES CT,TOWNS T,
DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID

GROUP BY CT.CITY --ÞEHÝR SAYISI 