USE ETRADE4
SELECT DISTINCT PAYMENTTYPE FROM PAYMENTS --ÝKÝ TÜR ÖDEME TÝPÝ VAR

SELECT PAYMENTTYPE AS ODEME_TURU,
SUM(PAYMENTTYPE) AS TOPLAMTUTAR
FROM PAYMENTS
GROUP BY PAYMENTTYPE  --ÖDEME TÜRÜNE GÖRE  TOPLAM TUTAR


--YUKARIDAKÝ SORGUDA ÖDEME TÜRÜ 1 VE 2 ÞEKLÝNDEYDÝ ÞÝMDÝ CASE WHEN METODU ÝLE ÝSÝM EKLEYECEÐÝZ
SELECT 
PAYMENTTYPE AS ODEME_TURU,
CASE 
	WHEN  PAYMENTTYPE=1 THEN 'KREDÝ_KARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESÝ'
END AS ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS
GROUP BY PAYMENTTYPE


--AYLARA GÖRE
SELECT 
DATEPART(YEAR,DATE_) AS YIL,
DATEPART(MONTH,DATE_) AS AY,
CASE 
	WHEN  PAYMENTTYPE=1 THEN 'KREDÝ_KARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESÝ'
END AS ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS
GROUP BY DATEPART(YEAR,DATE_) ,DATEPART(MONTH,DATE_) ,PAYMENTTYPE
ORDER BY  DATEPART(YEAR,DATE_) ,DATEPART(MONTH,DATE_)
