USE ETRADE4
--ürün kategorilerine göre sipariþ daðýlýmý
SELECT 
ITM.CATEGORY1,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID)AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O 
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

GROUP BY ITM.CATEGORY1
ORDER BY TOPLAMSIPARIS_TUTARI DESC

--EV KATEGORÝSÝNÝN ALTINDA EN ÇOK SATIÞ YAPAN KATEGORÝYÝ BULMAK ÝÇÝN
SELECT
ITM.CATEGORY1,ITM.CATEGORY2,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID)AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
WHERE ITM.CATEGORY1='EV' --OYUNCAK,KOZMETIK,GIDA,KAHVALTILIK,BEBEK,ET,SUT...
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2
ORDER BY TOPLAMSIPARIS_TUTARI DESC

--EV KATEGORÝSÝNÝN 3. ALT KATEGORÝSÝNÝ ÝNCELEYECEÐÝZ
SELECT
ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID)AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
WHERE ITM.CATEGORY1='EV'  --OYUNCAK,KOZMETIK,GIDA,KAHVALTILIK,BEBEK,ET,SUT...
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3
ORDER BY TOPLAMSIPARIS_TUTARI DESC

--EV KATEGORÝSÝNÝN 4. ALT KATEGORÝSÝNÝ ÝNCELEYECEÐÝZ
SELECT
ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID)AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
WHERE ITM.CATEGORY1='EV' --OYUNCAK,KOZMETIK,GIDA,KAHVALTILIK,BEBEK,ET,SUT...
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4
ORDER BY TOPLAMSIPARIS_TUTARI DESC


--ORTALAMA BÝRÝM FÝYAT 
SELECT
ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID)AS TOPLAMSIPARIS_SAYISI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMA_BIRIMFIYAT
FROM ORDERS O
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4
ORDER BY CATEGORY1
--BU SORGUDA 4. ALT KATEGORÝYE GÖRE SATIÞ FÝYATI VE SATIÞ ADEDÝNE GÖRE ORT BÝRÝM FÝYATI BULDUK
--3.,2. KATEGORÝYE GÖRE DE BULABÝLÝRDÝK