USE ETRADE4
--TARÝHE GÖRE SÝPARÝÞ DAÐILIMI
SELECT 
CONVERT(DATE,O.DATE_) TARIH,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID)AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O 
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY CONVERT(DATE,O.DATE_)
ORDER BY CONVERT(DATE,O.DATE_)


--AYLARA GÖRE SÝPARÝÞ DAÐILIMI
SELECT 
DATEPART(YEAR,O.DATE_) YIL,
DATEPART(MONTH,O.DATE_) AY,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID)AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O 
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)


--AYLARI SAYI OLARAK DEÐÝL DÝREKT ADI ÝLE KULLANMAK ÝSTERSEK

SELECT 
DATEPART(YEAR,O.DATE_) YIL,
DATEPART(MONTH,O.DATE_) AY,
CASE
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'ÞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NÝSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZÝRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AÐUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKÝM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
END AS AY_ADI,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID)AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O 
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)