USE ETRADE4
--ORTALAMA TESLÝMAT SÜRESÝ

SELECT
O.ID AS SIPARISID,
O.DATE_ AS SIPARISTARIHI,
I.DATE_ AS FATURATARIHI,
DATEDIFF(HOUR,O.DATE_,I.DATE_) AS TESLIMATSURESI_SAAT 
--AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS TESLIMATSURESI_SAAT ORT TESLÝMAT SÜRESÝ
FROM ORDERS O 
	INNER JOIN INVOICES I ON I.ORDERID=O.ID



--- ORTALAMA SÜRELER
SELECT
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENKISA_TESLIMATSURESI_SAAT,
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENUZUN_TESLIMATSURESI_SAAT,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORTALAMA_TESLIMATSURESI_SAAT
FROM ORDERS O 
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	

